version: '3'
services:
  app1:
    image: app1:latest
    ports:
    - "5001:5000"
  app2:
    image: app2:latest
    ports:
    - "5002:5000"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "8080:80"
    depends_on:
      - app1
      - app2
